from typing import Any, Dict, List
from urllib.parse import urlparse


BASE_SOURCES: List[Dict[str, Any]] = [
    {
        "url": "https://www.castingenbarcelona.es/",
        "nombre": "Casting en Barcelona",
        "categoria": "casting",
        "extraction_method": "rss",
        "priority_score": 95,
        "status": "verified",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Alta frecuencia y feed RSS estable",
    },
    {
        "url": "https://www.solocastings.es/castings-en/barcelona/",
        "nombre": "SoloCastings Barcelona",
        "categoria": "casting",
        "extraction_method": "rss",
        "priority_score": 92,
        "status": "verified",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": False,
        "exclude_latam": True,
        "notes": "Muy buen volumen en BCN",
    },
    {
        "url": "https://spainaudiovisualhub.digital.gob.es/ca/empleo",
        "nombre": "Spain Audiovisual Hub",
        "categoria": "institucional",
        "extraction_method": "playwright",
        "priority_score": 90,
        "status": "verified",
        "idioma": "es",
        "alcance_geografico": "es",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Directorio de bolsas y enlaces sectoriales",
    },
    {
        "url": "https://jobs.mediapro.tv/",
        "nombre": "Mediapro Jobs",
        "categoria": "corporate",
        "extraction_method": "playwright",
        "priority_score": 88,
        "status": "partial",
        "idioma": "es",
        "alcance_geografico": "es",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Corporativo con potencial alto",
    },
    {
        "url": "https://www.domestika.org/es/jobs/where/122-barcelona-espana",
        "nombre": "Domestika Jobs Barcelona",
        "categoria": "job_board",
        "extraction_method": "requests",
        "priority_score": 84,
        "status": "partial",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Roles creativos y multimedia",
    },
    {
        "url": "https://artfy.es/casting-barcelona/",
        "nombre": "Artfy Castings",
        "categoria": "casting",
        "extraction_method": "playwright",
        "priority_score": 83,
        "status": "partial",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": False,
        "exclude_latam": True,
        "notes": "Interesante pero inestable en scraping",
    },
    {
        "url": "https://www.actorsbarcelona.com/castings-en-barcelona",
        "nombre": "Actors Barcelona",
        "categoria": "casting",
        "extraction_method": "playwright",
        "priority_score": 80,
        "status": "verified",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": False,
        "exclude_latam": True,
        "notes": "Buena densidad de casting",
    },
    {
        "url": "https://apac.cat/es/bolsa-de-trabajo/",
        "nombre": "APAC",
        "categoria": "institucional",
        "extraction_method": "playwright",
        "priority_score": 78,
        "status": "partial",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Muy relevante sectorial; listados a veces vacíos",
    },
    {
        "url": "https://seleccio.3cat.cat/seleccio/index.jsf",
        "nombre": "3Cat Selecció",
        "categoria": "institucional",
        "extraction_method": "playwright",
        "priority_score": 77,
        "status": "partial",
        "idioma": "ca",
        "alcance_geografico": "es-catalunya",
        "include_remote": False,
        "exclude_latam": True,
        "notes": "Portal JSF complejo",
    },
    {
        "url": "https://www.rtve.es/aqui-hay-trabajo/",
        "nombre": "RTVE Aquí Hay Trabajo",
        "categoria": "institucional",
        "extraction_method": "playwright",
        "priority_score": 72,
        "status": "partial",
        "idioma": "es",
        "alcance_geografico": "es",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Mucho volumen general, filtrar rol",
    },
    {
        "url": "https://www.encast.pro/castings?cntry=ES",
        "nombre": "enCAST",
        "categoria": "casting",
        "extraction_method": "playwright",
        "priority_score": 70,
        "status": "partial",
        "idioma": "es",
        "alcance_geografico": "eu",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Interesante para captación secundaria",
    },
    {
        "url": "https://projectcasting.com/job?country=Spain",
        "nombre": "Project Casting",
        "categoria": "casting",
        "extraction_method": "playwright",
        "priority_score": 66,
        "status": "partial",
        "idioma": "en",
        "alcance_geografico": "eu",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Cobertura internacional",
    },
    {
        "url": "https://es.indeed.com/q-sector-audiovisual-l-barcelona-provincia-empleos.html",
        "nombre": "Indeed Audiovisual Barcelona",
        "categoria": "job_board",
        "extraction_method": "playwright_stealth",
        "priority_score": 50,
        "status": "blocked",
        "idioma": "es",
        "alcance_geografico": "es",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Bloqueo anti-bot alto",
    },
]


GENERALIST_SOURCES: List[Dict[str, Any]] = [
    {
        "url": "https://www.infojobs.net/jobsearch/search-results/list.xhtml?keyword=audiovisual&provinceIds=8",
        "nombre": "InfoJobs Audiovisual Barcelona",
        "categoria": "job_board_generalista",
        "extraction_method": "playwright_stealth",
        "priority_score": 78,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Generalista clave en España",
    },
    {
        "url": "https://www.infoempleo.com/trabajo/oferta-empleo/audiovisual/en_barcelona/",
        "nombre": "Infoempleo Audiovisual Barcelona",
        "categoria": "job_board_generalista",
        "extraction_method": "playwright",
        "priority_score": 72,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Generalista español con filtros",
    },
    {
        "url": "https://es.linkedin.com/jobs/search?keywords=audiovisual&location=Barcelona%2C%20Catalonia%2C%20Spain",
        "nombre": "LinkedIn Jobs Audiovisual Barcelona",
        "categoria": "job_board_generalista",
        "extraction_method": "playwright_stealth",
        "priority_score": 74,
        "status": "blocked",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Puede requerir login y bloqueo anti-bot",
    },
    {
        "url": "https://es.jooble.org/SearchResult?rgns=Barcelona&ukw=audiovisual",
        "nombre": "Jooble Audiovisual Barcelona",
        "categoria": "agregador_generalista",
        "extraction_method": "playwright",
        "priority_score": 68,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Agregador internacional con resultados locales",
    },
    {
        "url": "https://es.talent.com/jobs?k=audiovisual&l=Barcelona",
        "nombre": "Talent.com Audiovisual Barcelona",
        "categoria": "agregador_generalista",
        "extraction_method": "playwright",
        "priority_score": 66,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Agregador con volumen alto",
    },
    {
        "url": "https://www.jobisjob.es/barcelona/audiovisual/trabajos",
        "nombre": "JobisJob Audiovisual Barcelona",
        "categoria": "agregador_generalista",
        "extraction_method": "playwright",
        "priority_score": 64,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Agregador clásico en España",
    },
    {
        "url": "https://www.glassdoor.es/Empleo/barcelona-audiovisual-empleos-SRCH_IL.0,9_IC2510769_KO10,21.htm",
        "nombre": "Glassdoor Audiovisual Barcelona",
        "categoria": "job_board_generalista",
        "extraction_method": "playwright_stealth",
        "priority_score": 55,
        "status": "blocked",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Protección fuerte anti-bot",
    },
    {
        "url": "https://www.monster.es/trabajos/busqueda/?q=audiovisual&where=Barcelona",
        "nombre": "Monster Audiovisual Barcelona",
        "categoria": "job_board_generalista",
        "extraction_method": "playwright",
        "priority_score": 48,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Generalista internacional",
    },
    {
        "url": "https://www.adecco.es/ofertas-trabajo?k=audiovisual&l=Barcelona",
        "nombre": "Adecco Audiovisual Barcelona",
        "categoria": "ett_generalista",
        "extraction_method": "playwright",
        "priority_score": 60,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "ETT con ofertas puntuales de producción y eventos",
    },
    {
        "url": "https://www.randstad.es/candidatos/ofertas-empleo/?query=audiovisual&location=barcelona",
        "nombre": "Randstad Audiovisual Barcelona",
        "categoria": "ett_generalista",
        "extraction_method": "playwright",
        "priority_score": 58,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "ETT generalista",
    },
    {
        "url": "https://www.manpower.es/es/ofertas?q=audiovisual&l=barcelona",
        "nombre": "Manpower Audiovisual Barcelona",
        "categoria": "ett_generalista",
        "extraction_method": "playwright",
        "priority_score": 54,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "ETT generalista",
    },
    {
        "url": "https://www.hays.es/empleo?keywords=audiovisual&location=Barcelona",
        "nombre": "Hays Audiovisual Barcelona",
        "categoria": "consultora_rrhh",
        "extraction_method": "playwright",
        "priority_score": 50,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Consultora especializada",
    },
    {
        "url": "https://www.michaelpage.es/jobs/audiovisual/barcelona",
        "nombre": "Michael Page Audiovisual Barcelona",
        "categoria": "consultora_rrhh",
        "extraction_method": "playwright",
        "priority_score": 52,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Senior roles ocasionales",
    },
    {
        "url": "https://www.jobijoba.es/ofertas-empleo/audiovisual-empleos-en-barcelona",
        "nombre": "Jobijoba Audiovisual Barcelona",
        "categoria": "agregador_generalista",
        "extraction_method": "playwright",
        "priority_score": 56,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Meta-aggregador",
    },
    {
        "url": "https://www.turijobs.com/ofertas-trabajo?q=audiovisual&l=barcelona",
        "nombre": "Turijobs Audiovisual Barcelona",
        "categoria": "job_board_generalista",
        "extraction_method": "playwright",
        "priority_score": 42,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": False,
        "exclude_latam": True,
        "notes": "Menor relevancia, ocasional para eventos",
    },
    {
        "url": "https://www.milanuncios.com/ofertas-de-empleo-en-barcelona/?fromSearch=1&vendedor=profesional&q=audiovisual",
        "nombre": "Milanuncios Empleo Audiovisual Barcelona",
        "categoria": "clasificados",
        "extraction_method": "playwright",
        "priority_score": 40,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": False,
        "exclude_latam": True,
        "notes": "Clasificados; calidad variable",
    },
    {
        "url": "https://www.tablondeanuncios.com/trabajo-en-barcelona/audiovisual/",
        "nombre": "Tablon de Anuncios Audiovisual Barcelona",
        "categoria": "clasificados",
        "extraction_method": "requests",
        "priority_score": 39,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": False,
        "exclude_latam": True,
        "notes": "Clasificados locales",
    },
    {
        "url": "https://www.trabajos.com/ofertas-empleo/barcelona/audiovisual",
        "nombre": "Trabajos.com Audiovisual Barcelona",
        "categoria": "job_board_generalista",
        "extraction_method": "playwright",
        "priority_score": 52,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Generalista histórico",
    },
    {
        "url": "https://es.jooble.org/SearchResult?rgns=Barcelona&ukw=editor%20de%20video",
        "nombre": "Jooble Editor Video Barcelona",
        "categoria": "agregador_generalista",
        "extraction_method": "playwright",
        "priority_score": 63,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Query específica de edición",
    },
    {
        "url": "https://es.talent.com/jobs?k=ayudante+de+produccion&l=Barcelona",
        "nombre": "Talent.com Ayudante Produccion Barcelona",
        "categoria": "agregador_generalista",
        "extraction_method": "playwright",
        "priority_score": 61,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Query específica de ayudante producción",
    },
    {
        "url": "https://www.infojobs.net/jobsearch/search-results/list.xhtml?keyword=editor%20video&provinceIds=8",
        "nombre": "InfoJobs Editor Video Barcelona",
        "categoria": "job_board_generalista",
        "extraction_method": "playwright_stealth",
        "priority_score": 76,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Query específica de edición",
    },
    {
        "url": "https://www.infojobs.net/jobsearch/search-results/list.xhtml?keyword=realizador&provinceIds=8",
        "nombre": "InfoJobs Realizador Barcelona",
        "categoria": "job_board_generalista",
        "extraction_method": "playwright_stealth",
        "priority_score": 76,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Query específica de realización",
    },
    {
        "url": "https://www.infojobs.net/jobsearch/search-results/list.xhtml?keyword=operador%20camara&provinceIds=8",
        "nombre": "InfoJobs Operador Camara Barcelona",
        "categoria": "job_board_generalista",
        "extraction_method": "playwright_stealth",
        "priority_score": 75,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Query específica de operador",
    },
    {
        "url": "https://www.infojobs.net/jobsearch/search-results/list.xhtml?keyword=ayudante%20produccion&provinceIds=8",
        "nombre": "InfoJobs Ayudante Produccion Barcelona",
        "categoria": "job_board_generalista",
        "extraction_method": "playwright_stealth",
        "priority_score": 75,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Query específica de ayudante producción",
    },
    {
        "url": "https://www.jobted.es/trabajo-editor-video-en-barcelona",
        "nombre": "Jobted Editor Video Barcelona",
        "categoria": "agregador_generalista",
        "extraction_method": "requests",
        "priority_score": 60,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Query específica de edición",
    },
    {
        "url": "https://www.jobted.es/trabajo-ayudante-produccion-en-barcelona",
        "nombre": "Jobted Ayudante Produccion Barcelona",
        "categoria": "agregador_generalista",
        "extraction_method": "requests",
        "priority_score": 60,
        "status": "candidate",
        "idioma": "es",
        "alcance_geografico": "es-catalunya",
        "include_remote": True,
        "exclude_latam": True,
        "notes": "Query específica de ayudante de producción",
    },
]


def _dedupe_sources(sources: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    deduped: List[Dict[str, Any]] = []
    seen_urls = set()
    for source in sources:
        url = source.get("url")
        if not url or url in seen_urls:
            continue
        seen_urls.add(url)
        deduped.append(source)
    return deduped


SOURCE_REGISTRY: List[Dict[str, Any]] = _dedupe_sources(
    BASE_SOURCES + GENERALIST_SOURCES
)


def get_registry(include_blocked: bool = False) -> List[Dict[str, Any]]:
    if include_blocked:
        return SOURCE_REGISTRY[:]
    return [s for s in SOURCE_REGISTRY if s.get("status") != "blocked"]


def get_prioritized_urls(limit: int = 20, include_blocked: bool = False) -> List[str]:
    sources = sorted(
        get_registry(include_blocked=include_blocked),
        key=lambda x: int(x.get("priority_score", 0)),
        reverse=True,
    )
    return [s["url"] for s in sources[:limit]]


def to_catalog_rows(include_blocked: bool = False) -> List[Dict[str, Any]]:
    rows = []
    for source in get_registry(include_blocked=include_blocked):
        domain = urlparse(source["url"]).netloc.lower()
        row = dict(source)
        row["domain"] = domain
        rows.append(row)
    return rows
